name: Cypress Tests

on:
  push:
    branches: [ master ]
    
jobs:
  install:
    runs-on: ubuntu-18.04
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cypress Install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
        
      - run: yarn cypress info
      - run: node -p 'os.cpus()'
      - run: CI=false yarn build
      
      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build
          
  ui-chrome-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    needs: install
    strategy:
      fail-fast: false
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
          
      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome"
          spec: cypress/integration/*
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
